apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ClusterResourcePlacement
metadata:
  name: guestbook-crp
spec:
  policy:
    placementType: PickAll
    affinity:
      clusterAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          clusterSelectorTerms:
            - labelSelector:
                matchExpressions:
                  - key: fleet.azure.com/group
                    operator: In
                    values:
                      - staging
                      - canary
                      - production
  resourceSelectors:
    - group: ""
      kind: Namespace
      name: argocd
      version: v1
  revisionHistoryLimit: 10
  strategy:
    type: External
