apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ResourcePlacement
metadata:
  name: team-a-governance-rp
  namespace: team-a-demo
spec:
  resourceSelectors:
    - group: ""
      kind: ResourceQuota
      version: v1
      labelSelector:
        matchLabels:
          fleet-demo.azure.com/component: platform-governance
    - group: ""
      kind: LimitRange
      version: v1
      labelSelector:
        matchLabels:
          fleet-demo.azure.com/component: platform-governance
    - group: networking.k8s.io
      kind: NetworkPolicy
      version: v1
      labelSelector:
        matchLabels:
          fleet-demo.azure.com/component: platform-governance
  policy:
    placementType: PickAll
    affinity:
      clusterAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          clusterSelectorTerms:
            - labelSelector:
                matchExpressions:
                  - key: fleet.azure.com/group
                    operator: In
                    values:
                      - staging
                      - canary
                      - production