apiVersion: v1
kind: LimitRange
metadata:
  name: team-a-default-limits
  namespace: team-a-demo
  labels:
    app.kubernetes.io/name: team-a-governance
    fleet-demo.azure.com/component: platform-governance
    fleet-demo.azure.com/use-case: namespace-placement
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      default:
        cpu: 200m
        memory: 256Mi