apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-a-quota
  namespace: team-a-demo
  labels:
    app.kubernetes.io/name: team-a-governance
    fleet-demo.azure.com/component: platform-governance
    fleet-demo.azure.com/use-case: namespace-placement
spec:
  hard:
    requests.cpu: "500m"
    limits.cpu: "1"
    requests.memory: 512Mi
    limits.memory: 1Gi
    pods: "10"